name: latentgee

channels:
  - conda-forge
  - pytorch
  - defaults

dependencies:
  - python=3.10

  - numpy=1.26
  - pandas=2.1
  - scipy=1.11
  - scikit-learn
  - statsmodels
  - matplotlib
  - numba=0.59
  - umap-learn
  - openpyxl
  - pyyaml

  - ipykernel
  - ipywidgets

  # PyTorch (CPU)
  - pytorch=2.2
  - cpuonly

  # clustering / bio
  - hdbscan
  - scikit-bio
  - optuna==3.6.1
  - pip
